### ISSUE TITLE
和flubber的区别

### ISSUE THREAD

**Issue by jiankafei** [AlloyTeam/pasition#1]
pasition和flubber太像了，演示都差不多。两个是同一个东西吗，还是谁抄谁？

**Comment by dntzhang** [comment]
问得好！  你如果看过 flubber 源码和  pasition 源码的话，你会发现:
 
- flubber 和 pasition 的算法完全不同
- flubber 和 pasition 的API设计完全不同

而且 flubber 的架构貌似决定了它是不支持 stroke 模式的 :)

**Comment by jiankafei** [comment]
多谢，了解了！
