### ISSUE TITLE
Is there any limitations or restrictions when use pasition to implement morph effects?

### ISSUE THREAD

**Issue by Rowandjj** [AlloyTeam/pasition#4]
我见过有很多类似的库可以实现svg 变形动画(morph)比如flubber，但是绝大部分都有一些限制，比如变形的两个path必须保证具有相同的绘制命令。想知道pasition是否对path有额外的限制还是说任意两个path都可以很好的变形?

**Comment by dntzhang** [comment]
任意path都行，pasition内部会转换~~
