### ISSUE TITLE
算法上有点疑惑

### ISSUE THREAD

**Issue by Rowandjj** [AlloyTeam/pasition#5]
Hi，最近看了下pasition的算法，有个疑惑的地方：

<img width="782" alt="2018-07-18 3 00 16" src="https://user-images.githubusercontent.com/5766252/42865150-53837f94-8a9b-11e8-9196-fe4aecca9628.png">

`_preprocessing` 函数中有个splitCurves的操作，我理解目的应该是让两个path的curves的数目保持一致，但是这里为啥MIN_CURVES_COUNT=100的限制，假设curves的长度很小，那么会填充到100的长度，这个过程应该很耗时吧？

**Comment by dntzhang** [comment]
确实耗时，但是没想象中耗时，计算量不大，分割得越多最短路径找得越准确。
